#! /bin/bash

if [  -n "$(pgrep -f  Scheduler
then
echo Scheduler is running, kill it first. Exiting...
exit
fi

if  [ "$1" = "nolog" ] ; then

 java -cp /home/pi/Scheduler:/home/pi/git/Scheduler/lib/'*':/home/pi/git/Scheduler/lib/'*' scheduler/Scheduler

else

 loglink=/home/pi/Scheduler/logs/Schedulerlogfile
 logfile=/home/pi/Scheduler/logs/log-`date +%d-%m@%H:%M`
 [ -f $loglink ] && rm $loglink
 touch $logfile
 ln -s $logfile $loglink

 (
 cd /home/pi/git/Scheduler/run
 java -cp /home/pi/Scheduler:/home/pi/git/Scheduler/lib/'*' scheduler/Scheduler
 )  >> $loglink 2>&1 &

fi
